# Dev image for live reload
FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat \
  && apk add --no-cache \
    --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community \
    typst \
    font-noto \
    font-noto-cjk \
    font-noto-emoji

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY package.json pnpm-lock.yaml* ./
RUN pnpm i --frozen-lockfile

COPY . .

ENV PORT=3000
ENV HOSTNAME=0.0.0.0

EXPOSE 3000

CMD ["pnpm", "dev"]
